update future apis
KyberNetwork/binance-client pull request #2
Opened 2021-06-23 07:45 UTC by halink0803

2021-06-25 07:21 UTC, NNagato requested changes

2021-06-25 07:21 UTC, NNagato commented on README.md
> +source api docs: https://binance-docs.github.io
pls replace this link to https://binance-docs.github.io/apidocs, current link lead to 404 page

2021-06-25 07:21 UTC, NNagato commented on future.go
> +		response CreateOrderResult
this response type is for spot, future API return more data https://binance-docs.github.io/apidocs/futures/en/#new-order-trade. the param tradeType is not used in this function and refer from the docs there are more params can be supported in this api

2021-06-25 07:21 UTC, NNagato commented on future.go
> +		response FutureAccountBalance
this api return an array

2021-07-07 06:25 UTC, NNagato requested changes

2021-07-07 06:25 UTC, NNagato commented on future.go
> +	price, stopPrice, activationPrice, callbackRate, quantity float64) (CreateOrderResult, error) {
CreateOrderResult is for spot order, please create a new type for future order

2021-07-07 06:25 UTC, NNagato commented on future.go
> +func (bc *Client) GetPositionInformation() ([]PositionInformation, error) {
this API has symbol param as optional

2021-07-07 07:11 UTC, halink0803 commented
@NNagato pls re-check it.

2021-07-07 08:42 UTC, NNagato approved these changes
LGTM

2021-07-07 10:00 UTC, merged